test.name=nmae from properties file
#spring.profiles.active=dev
server.port=8081
server.servlet.context-path=/springootbasic

logging.file.name=c://springootbasic/log.log
logging.logback.rollingpolicy.max-file-size=5mb
logging.logback.rollingpolicy.max-history=5
logging.logback.rollingpolicy.file-name-pattern=c://springootbasic/log-%d{yyyy-MM-dd}.%i.log


spring.jpa.hibernate.ddl-auto = update
spring.datasource.username =postgres
spring.datasource.password =postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.zipkin.base-url=http://localhost:9411/

# Show Spring transaction logs
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# Actuator endpoints: expose heapdump and other useful endpoints
management.endpoints.web.exposure.include=health,info,heapdump,threaddump,metrics,env,caches
management.endpoint.heapdump.enabled=true
management.endpoints.web.base-path=/actuator


spring.config.use-legacy-processing=true