#spring.profiles.active=dev

server.port=8080
server.servlet.context-path=/springootbasic

logging.file.name=c://springootbasic/log.log
logging.logback.rollingpolicy.max-file-size=5mb
logging.logback.rollingpolicy.max-history=5
logging.logback.rollingpolicy.file-name-pattern=c://springootbasic/log-%d{yyyy-MM-dd}.%i.log


spring.jpa.hibernate.ddl-auto = create
spring.datasource.username =postgres
spring.datasource.password =postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.zipkin.base-url=http://localhost:9411/
spring.application.name=MainService